#!/usr/bin/env zsh

brew cask install tuxera-ntfs
brew cask install authy
brew cask install google-chrome
brew cask install google-backup-and-sync
brew cask install google-drive-file-stream
brew cask install dropbox
brew cask install alfred
brew cask install bartender
brew cask install istat-menus
brew cask install notion
brew cask install slack
brew cask install firefox
brew cask install snagit
brew cask install screenflow
brew cask install marked
brew cask install deckset
brew cask install visual-studio-code
brew cask install atom
brew cask install sublime-text
brew cask install sourcetree
brew cask install dash
brew cask install paw
brew cask install sketch
brew cask install studio-3t
brew cask install sequel-pro
brew cask install teamviewer
brew cask install docker
brew cask install virtualbox
brew cask install android-studio
brew cask install unity-hub
brew cask install mplayerx
brew cask install handbrake
brew cask install adapter
